name: Publish Workflow Manifest

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write  # Required to push to gh-pages branch
  pages: write     # Required to deploy to GitHub Pages
  id-token: write  # Required for GitHub Pages deployment

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: |
          cd agora-analyst-python
          pip install -r requirements.txt
      
      - name: Generate Manifest File
        run: |
          cd agora-analyst-python
          python main.py describe-workflows > workflow-manifest.json
          
      - name: Verify Manifest
        run: |
          cd agora-analyst-python
          echo "Generated manifest:"
          cat workflow-manifest.json
          echo ""
          echo "Validating JSON..."
          python -m json.tool workflow-manifest.json > /dev/null && echo "✅ Valid JSON"
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./agora-analyst-python
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
